### ISSUE TITLE
Multiple SSH keys possible

### ISSUE THREAD

**Issue by jasonpabbott** [cchurch/ansible-role-admin-users#1]
Hi Chris, I like the role, helpful with my new ansible environment, I was wondering how I would easily add multiple SSH keys to a user?  Thanks

**Comment by cchurch** [comment]
That's something I've considered adding.  The workaround for now is just to duplicate a user entry and specify a different key for each:

```
- username: jim
  fullname: "Jim User"
  pubkey: "ssh-rsa key1"
- username: jim
  fullname: "Jim User"
  pubkey: "ssh-rsa key2"
```

**Comment by jasonpabbott** [comment]
Awesome, that works

**Comment by lingfish** [comment]
I'd like to see this added too -- quite useful for when you have a generic "last resort" account across many VMs, and a team of admins... or perhaps, a user used for cron-based Ansible runs.

**Comment by cchurch** [comment]
I would like to add this feature, reopening.

**Comment by cchurch** [comment]
Has been added in 0.7.0 via 328ff38c88d1c25fb5f9659eb6cb20c5044a409d. `pubkey` can now be a list of strings containing public keys or URLs, but still works if it is only a single string.
