### ISSUE TITLE
Create per-user primary groups.

### ISSUE THREAD

**Issue by cchurch** [cchurch/ansible-role-admin-users#4]
Implement changes from https://github.com/adamherzog/ansible-role-admin-users/commit/efcd6db4c6bbd9cfb34a1139b04d8b696422f578

**Comment by lingfish** [comment]
Hi, just wondering if these two issues will get done?

**Comment by cchurch** [comment]
@lingfish Yes, I'll work on an update to include this one and #5.

**Comment by lingfish** [comment]
Nice, ta. I'll be throwing one or PRs to you as well :)

**Comment by cchurch** [comment]
Implemented in d2460aeb997201a356d6f33a87763ba2ab8d8676 and 6587664f033dcddcfcbd8bf716712c3ab978565e, included in [0.6.0](https://github.com/cchurch/ansible-role-admin-users/releases/tag/0.6.0).
